version: 2
project_name: icignore

before:
  hooks:
    - go mod tidy

builds:
  - id: icignore
    main: ./cmd/icignore
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

homebrew_casks:
  - name: icignore
    # use darwin archives to generate a cask
    # ids: [archive]
    binary: icignore
    repository:
      owner: mathis-lambert
      name: homebrew-icloud-ignore
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaser
      email: noreply@goreleaser
    homepage: "https://github.com/mathis-lambert/icloud-ignore"
    description: "Exclude iCloud folders via .nosync suffix while keeping symlinks for seamless access."
    license: MIT
    hooks:
      post:
        # remove quarantine so the unsigned binary runs without prompts
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/icignore"]
          end

checksum:
  name_template: "checksums_{{ .Version }}.txt"

changelog:
  sort: asc
  use: git

release:
  mode: replace
  github:
    owner: mathis-lambert
    name: icloud-ignore
