name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  goreleaser:
    environment: env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21"

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v3.0.0
          args: release --clean
        env:
          # Token used by GoReleaser to publish release in this repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PAT (environment secret) used to push to the private tap repo
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
